services:
  mysql:
    image: mariadb:11
    container_name: kiwify-server-database
    ports:
      - "33067:3306"
    environment:
      MARIADB_ROOT_PASSWORD: ${DATABASE_ROOT_PASSWORD}
      MARIADB_DATABASE: ${DATABASE_NAME}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-net
  
volumes:
  db_data:
networks:
  app-net:
    driver: bridge